[project]
name = "rag-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abram", email = "abramhany9@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=3.19.2",
    "pypdf2>=3.0.1",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
rag-from-scratch = "rag_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
